-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
-- Generated by Scripts/ws_tools.py seed-sql
SET client_min_messages TO WARNING;

INSERT INTO ws_role (role_code) VALUES
    ('user'),
    ('author'),
    ('moderator'),
    ('admin');

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'reader1', 'Читатель тестовых утечек', r.role_id, '192.168.1.10'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'user';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'author1', 'Основной автор документов', r.role_id, '10.0.0.2'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'author';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'coauthor1', 'Соавтор', r.role_id, '10.0.0.3'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'author';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'mod1', 'Модератор раздела', r.role_id, '172.16.0.5'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'moderator';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'admin1', 'Администратор системы', r.role_id, '172.16.0.1'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'admin';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'safe3_user', 'Пользователь с 3 активными safe IP', r.role_id, '10.10.10.10'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'user';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'safe3_author', 'Автор с 3 активными safe IP', r.role_id, '10.20.20.20'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'author';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'blocked_user', 'Пользователь сейчас заблокирован', r.role_id, '198.51.100.200'::inet, TRUE
FROM ws_role r WHERE r.role_code = 'user';

INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)
SELECT 'risk_user', 'Учётная запись с историей блокировки', r.role_id, '203.0.113.50'::inet, FALSE
FROM ws_role r WHERE r.role_code = 'user';

INSERT INTO ws_theme (name, description, parent_id) VALUES
    ('Политика', 'Государство и власть', NULL);

INSERT INTO ws_theme (name, description, parent_id)
SELECT 'Выборы', 'Избирательные кампании', t.theme_id FROM ws_theme t WHERE t.name = 'Политика' LIMIT 1;

INSERT INTO ws_theme (name, description, parent_id) VALUES
    ('Экономика', 'Рынки и финансы', NULL);

INSERT INTO ws_informant (external_code, extra_info, categories) VALUES
    ('INF-ORG-01', 'Условная организация-источник', ARRAY['орг']),
    ('INF-PER-07', 'Условное физлицо', ARRAY['физлицо']);

INSERT INTO ws_document (title, doc_type, primary_author_id, extra_info)
SELECT 'Сводная таблица по контрактам', 'table', u.user_id, 'Демо-документ 1'
FROM ws_user u WHERE u.login = 'author1';

INSERT INTO ws_document (title, doc_type, primary_author_id, extra_info)
SELECT 'Внутренняя переписка (фрагмент)', 'text', u.user_id, 'Демо-документ 2'
FROM ws_user u WHERE u.login = 'author1';

INSERT INTO ws_document_coauthor (document_id, coauthor_id)
SELECT d.document_id, u.user_id
FROM ws_document d
CROSS JOIN ws_user u
WHERE d.title = 'Внутренняя переписка (фрагмент)' AND u.login = 'coauthor1';

INSERT INTO ws_document_version (
    document_id, version_no, previous_version_id, created_at,
    edited_by_user_id, informant_id, body_preview
)
SELECT d.document_id, 1, NULL, TIMESTAMPTZ '2025-01-10 12:00:00+00',
       u.user_id, i.informant_id, 'Строки 1–20'
FROM ws_document d
JOIN ws_user u ON u.login = 'author1'
JOIN ws_informant i ON i.external_code = 'INF-ORG-01'
WHERE d.title = 'Сводная таблица по контрактам';

INSERT INTO ws_document_version (
    document_id, version_no, previous_version_id, created_at,
    edited_by_user_id, informant_id, body_preview
)
SELECT d.document_id, 2, v.version_id, TIMESTAMPTZ '2025-01-15 09:30:00+00',
       uc.user_id, i.informant_id, 'Строки 1–35'
FROM ws_document d
JOIN ws_document_version v ON v.document_id = d.document_id AND v.version_no = 1
JOIN ws_user uc ON uc.login = 'coauthor1'
JOIN ws_informant i ON i.external_code = 'INF-PER-07'
WHERE d.title = 'Сводная таблица по контрактам';

INSERT INTO ws_document_version (
    document_id, version_no, previous_version_id, created_at,
    edited_by_user_id, informant_id, body_preview
)
SELECT d.document_id, 1, NULL, TIMESTAMPTZ '2025-02-01 18:00:00+00',
       u.user_id, i.informant_id, 'Заголовки писем'
FROM ws_document d
JOIN ws_user u ON u.login = 'author1'
JOIN ws_informant i ON i.external_code = 'INF-PER-07'
WHERE d.title = 'Внутренняя переписка (фрагмент)';

INSERT INTO ws_version_theme (version_id, theme_id)
SELECT v.version_id, t.theme_id
FROM ws_document_version v
JOIN ws_document d ON d.document_id = v.document_id
JOIN ws_theme t ON t.name = 'Экономика'
WHERE d.title = 'Сводная таблица по контрактам' AND v.version_no = 1;

INSERT INTO ws_version_theme (version_id, theme_id)
SELECT v.version_id, t.theme_id
FROM ws_document_version v
JOIN ws_document d ON d.document_id = v.document_id
JOIN ws_theme t ON t.name IN ('Политика', 'Экономика')
WHERE d.title = 'Сводная таблица по контрактам' AND v.version_no = 2;

INSERT INTO ws_version_theme (version_id, theme_id)
SELECT v.version_id, t.theme_id
FROM ws_document_version v
JOIN ws_document d ON d.document_id = v.document_id
JOIN ws_theme t ON t.name = 'Политика'
WHERE d.title = 'Внутренняя переписка (фрагмент)' AND v.version_no = 1;

INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)
SELECT v.version_id, m.user_id, 'ready_for_publish'::ws_moderation_status,
       TIMESTAMPTZ '2025-01-11 08:00:00+00', 'Ок к публикации'
FROM ws_document_version v
JOIN ws_document d ON d.document_id = v.document_id
JOIN ws_user m ON m.login = 'mod1'
WHERE d.title = 'Сводная таблица по контрактам' AND v.version_no = 1;

INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)
SELECT v.version_id, m.user_id, 'sent_for_revision'::ws_moderation_status,
       TIMESTAMPTZ '2025-01-16 10:00:00+00', 'Нужны ссылки на первоисточник'
FROM ws_document_version v
JOIN ws_document d ON d.document_id = v.document_id
JOIN ws_user m ON m.login = 'mod1'
WHERE d.title = 'Сводная таблица по контрактам' AND v.version_no = 2;

INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)
SELECT v.version_id, m.user_id, 'rejected'::ws_moderation_status,
       TIMESTAMPTZ '2025-02-02 11:00:00+00', 'Персональные данные'
FROM ws_document_version v
JOIN ws_document d ON d.document_id = v.document_id
JOIN ws_user m ON m.login = 'mod1'
WHERE d.title = 'Внутренняя переписка (фрагмент)' AND v.version_no = 1;

INSERT INTO ws_favorite (user_id, document_id, added_at)
SELECT u.user_id, d.document_id, TIMESTAMPTZ '2025-03-01 12:00:00+00'
FROM ws_user u
CROSS JOIN ws_document d
WHERE u.login = 'reader1' AND d.title = 'Сводная таблица по контрактам';

INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)
SELECT u.user_id, d.document_id, TIMESTAMPTZ '2025-03-05 14:22:00+00', '192.168.1.10'::inet
FROM ws_user u
CROSS JOIN ws_document d
WHERE u.login = 'reader1' AND d.title = 'Сводная таблица по контрактам';

INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)
SELECT u.user_id, d.document_id, TIMESTAMPTZ '2025-03-06 09:10:00+00', '192.168.1.10'::inet
FROM ws_user u
CROSS JOIN ws_document d
WHERE u.login = 'reader1' AND d.title = 'Внутренняя переписка (фрагмент)';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '203.0.113.1'::inet, TIMESTAMPTZ '2025-01-01 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'risk_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '203.0.113.2'::inet, TIMESTAMPTZ '2025-01-02 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'risk_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.0.0.10'::inet, TIMESTAMPTZ '2025-01-05 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'safe3_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.0.0.11'::inet, TIMESTAMPTZ '2025-01-06 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'safe3_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.0.0.12'::inet, TIMESTAMPTZ '2025-01-07 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'safe3_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.0.0.13'::inet, TIMESTAMPTZ '2025-01-08 00:00:00+00', FALSE
FROM ws_user u WHERE u.login = 'safe3_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.1.0.1'::inet, TIMESTAMPTZ '2025-01-09 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'safe3_author';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.1.0.2'::inet, TIMESTAMPTZ '2025-01-10 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'safe3_author';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.1.0.3'::inet, TIMESTAMPTZ '2025-01-11 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'safe3_author';

INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)
SELECT u.user_id, '198.51.100.99'::inet, TIMESTAMPTZ '2025-04-01 07:00:00+00', 'Подозрительный вход'
FROM ws_user u WHERE u.login = 'risk_user';

INSERT INTO ws_block_event (user_id, event_type, occurred_at, comment_text, actor_id)
SELECT u.user_id, 'blocked', TIMESTAMPTZ '2025-04-01 07:01:00+00',
       'Автоблокировка: IP не в списке доверенных', NULL
FROM ws_user u WHERE u.login = 'risk_user';

UPDATE ws_user SET is_blocked = TRUE WHERE login = 'risk_user';

INSERT INTO ws_block_event (user_id, event_type, occurred_at, comment_text, actor_id)
SELECT u.user_id, 'unblocked', TIMESTAMPTZ '2025-04-02 10:00:00+00',
       'Проверка личности пройдена', m.user_id
FROM ws_user u
CROSS JOIN ws_user m
WHERE u.login = 'risk_user' AND m.login = 'mod1';

UPDATE ws_user SET is_blocked = FALSE WHERE login = 'risk_user';

INSERT INTO ws_block_event (user_id, event_type, occurred_at, comment_text, actor_id)
SELECT u.user_id, 'blocked', TIMESTAMPTZ '2025-04-03 08:15:00+00',
       'Автоблокировка: чтение с неизвестного IP', NULL
FROM ws_user u WHERE u.login = 'blocked_user';

INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)
SELECT u.user_id, '10.250.1.1'::inet, TIMESTAMPTZ '2025-01-15 00:00:00+00', TRUE
FROM ws_user u WHERE u.login = 'blocked_user';

INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)
SELECT u.user_id, '198.51.100.200'::inet, NOW() - make_interval(days => 3), 'свежий вход с другого IP (заблокирован)'
FROM ws_user u WHERE u.login = 'blocked_user';

INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)
SELECT d.document_id, ua.user_id, NULL, um.user_id,
       'Упоминаю @mod1: нужна ли публикация в открытом доступе?',
       TIMESTAMPTZ '2025-03-10 16:00:00+00', '10.0.0.2'::inet
FROM ws_document d
JOIN ws_user ua ON ua.login = 'author1'
JOIN ws_user um ON um.login = 'mod1'
WHERE d.title = 'Сводная таблица по контрактам';

INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)
SELECT d.document_id, ur.user_id, c.comment_id, NULL,
       'Согласен с замечанием модератора по версии 2.',
       TIMESTAMPTZ '2025-03-11 11:30:00+00', '192.168.1.10'::inet
FROM ws_document d
JOIN ws_user ur ON ur.login = 'reader1'
JOIN ws_comment c ON c.document_id = d.document_id AND c.author_id = (SELECT user_id FROM ws_user WHERE login = 'author1')
WHERE d.title = 'Сводная таблица по контрактам'
LIMIT 1;

INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)
SELECT d.document_id, um.user_id, c2.comment_id, ua.user_id,
       'Ответ @reader1: учту, доработаю и пришлю новую версию.',
       TIMESTAMPTZ '2025-03-11 12:05:00+00', '10.0.0.2'::inet
FROM ws_document d
JOIN ws_user um ON um.login = 'mod1'
JOIN ws_user ua ON ua.login = 'author1'
JOIN ws_comment c2 ON c2.document_id = d.document_id AND c2.author_id = (SELECT user_id FROM ws_user WHERE login = 'reader1')
WHERE d.title = 'Сводная таблица по контрактам'
LIMIT 1;
