#!/usr/bin/env python3

from __future__ import annotations

import argparse
import random
import string
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable


def _sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _sql_text_array(items: Iterable[str]) -> str:
    return "ARRAY[" + ", ".join(_sql_str(x) for x in items) + "]"


def _sql_ident(s: str) -> str:
    return s


def _sql_inet(ip: str) -> str:
    return f"{_sql_str(ip)}::inet"


def _sql_timestamptz(ts: str) -> str:
    return f"TIMESTAMPTZ {_sql_str(ts)}"


def _join_statements(stmts: Iterable[str]) -> str:
    out: list[str] = []
    for s in stmts:
        s = s.strip()
        if not s:
            continue
        if not s.endswith(";"):
            s += ";"
        out.append(s)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


@dataclass(frozen=True)
class SeedUser:
    login: str
    extra_info: str
    role_code: str
    last_ip: str
    is_blocked: bool


def render_seed_sql() -> str:
    header = "\n".join(
        [
            "-- AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.",
            "-- Generated by Scripts/ws_tools.py seed-sql",
            "",
        ]
    )
    roles = ["user", "author", "moderator", "admin"]

    users = [
        SeedUser("reader1", "Читатель тестовых утечек", "user", "192.168.1.10", False),
        SeedUser("author1", "Основной автор документов", "author", "10.0.0.2", False),
        SeedUser("coauthor1", "Соавтор", "author", "10.0.0.3", False),
        SeedUser("mod1", "Модератор раздела", "moderator", "172.16.0.5", False),
        SeedUser("admin1", "Администратор системы", "admin", "172.16.0.1", False),
        SeedUser("safe3_user", "Пользователь с 3 активными safe IP", "user", "10.10.10.10", False),
        SeedUser("safe3_author", "Автор с 3 активными safe IP", "author", "10.20.20.20", False),
        SeedUser("blocked_user", "Пользователь сейчас заблокирован", "user", "198.51.100.200", True),
        SeedUser("risk_user", "Учётная запись с историей блокировки", "user", "203.0.113.50", False),
    ]

    stmts: list[str] = []
    stmts.append("SET client_min_messages TO WARNING")

    role_values = ",\n    ".join(f"({_sql_str(r)})" for r in roles)
    stmts.append(
        "\n".join(
            [
                f"INSERT INTO {_sql_ident('ws_role')} (role_code) VALUES",
                f"    {role_values}",
            ]
        )
    )

    for u in users:
        stmts.append(
            "\n".join(
                [
                    "INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)",
                    f"SELECT {_sql_str(u.login)}, {_sql_str(u.extra_info)}, r.role_id, {_sql_inet(u.last_ip)}, {'TRUE' if u.is_blocked else 'FALSE'}",
                    "FROM ws_role r WHERE r.role_code = " + _sql_str(u.role_code),
                ]
            )
        )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_theme (name, description, parent_id) VALUES",
                f"    ({_sql_str('Политика')}, {_sql_str('Государство и власть')}, NULL)",
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_theme (name, description, parent_id)",
                "SELECT "
                + f"{_sql_str('Выборы')}, {_sql_str('Избирательные кампании')}, t.theme_id "
                + "FROM ws_theme t WHERE t.name = " + _sql_str("Политика") + " LIMIT 1",
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_theme (name, description, parent_id) VALUES",
                f"    ({_sql_str('Экономика')}, {_sql_str('Рынки и финансы')}, NULL)",
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_informant (external_code, extra_info, categories) VALUES",
                f"    ({_sql_str('INF-ORG-01')}, {_sql_str('Условная организация-источник')}, {_sql_text_array(['орг'])}),",
                f"    ({_sql_str('INF-PER-07')}, {_sql_str('Условное физлицо')}, {_sql_text_array(['физлицо'])})",
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_document (title, doc_type, primary_author_id, extra_info)",
                f"SELECT {_sql_str('Сводная таблица по контрактам')}, {_sql_str('table')}, u.user_id, {_sql_str('Демо-документ 1')}",
                "FROM ws_user u WHERE u.login = " + _sql_str("author1"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_document (title, doc_type, primary_author_id, extra_info)",
                f"SELECT {_sql_str('Внутренняя переписка (фрагмент)')}, {_sql_str('text')}, u.user_id, {_sql_str('Демо-документ 2')}",
                "FROM ws_user u WHERE u.login = " + _sql_str("author1"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_document_coauthor (document_id, coauthor_id)",
                "SELECT d.document_id, u.user_id",
                "FROM ws_document d",
                "CROSS JOIN ws_user u",
                "WHERE d.title = "
                + _sql_str("Внутренняя переписка (фрагмент)")
                + " AND u.login = "
                + _sql_str("coauthor1"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_document_version (",
                "    document_id, version_no, previous_version_id, created_at,",
                "    edited_by_user_id, informant_id, body_preview",
                ")",
                "SELECT d.document_id, 1, NULL, "
                + _sql_timestamptz("2025-01-10 12:00:00+00")
                + ",",
                "       u.user_id, i.informant_id, " + _sql_str("Строки 1–20"),
                "FROM ws_document d",
                "JOIN ws_user u ON u.login = " + _sql_str("author1"),
                "JOIN ws_informant i ON i.external_code = " + _sql_str("INF-ORG-01"),
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_document_version (",
                "    document_id, version_no, previous_version_id, created_at,",
                "    edited_by_user_id, informant_id, body_preview",
                ")",
                "SELECT d.document_id, 2, v.version_id, "
                + _sql_timestamptz("2025-01-15 09:30:00+00")
                + ",",
                "       uc.user_id, i.informant_id, " + _sql_str("Строки 1–35"),
                "FROM ws_document d",
                "JOIN ws_document_version v ON v.document_id = d.document_id AND v.version_no = 1",
                "JOIN ws_user uc ON uc.login = " + _sql_str("coauthor1"),
                "JOIN ws_informant i ON i.external_code = " + _sql_str("INF-PER-07"),
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_document_version (",
                "    document_id, version_no, previous_version_id, created_at,",
                "    edited_by_user_id, informant_id, body_preview",
                ")",
                "SELECT d.document_id, 1, NULL, "
                + _sql_timestamptz("2025-02-01 18:00:00+00")
                + ",",
                "       u.user_id, i.informant_id, " + _sql_str("Заголовки писем"),
                "FROM ws_document d",
                "JOIN ws_user u ON u.login = " + _sql_str("author1"),
                "JOIN ws_informant i ON i.external_code = " + _sql_str("INF-PER-07"),
                "WHERE d.title = " + _sql_str("Внутренняя переписка (фрагмент)"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_version_theme (version_id, theme_id)",
                "SELECT v.version_id, t.theme_id",
                "FROM ws_document_version v",
                "JOIN ws_document d ON d.document_id = v.document_id",
                "JOIN ws_theme t ON t.name = " + _sql_str("Экономика"),
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам") + " AND v.version_no = 1",
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_version_theme (version_id, theme_id)",
                "SELECT v.version_id, t.theme_id",
                "FROM ws_document_version v",
                "JOIN ws_document d ON d.document_id = v.document_id",
                "JOIN ws_theme t ON t.name IN (" + ", ".join(map(_sql_str, ["Политика", "Экономика"])) + ")",
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам") + " AND v.version_no = 2",
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_version_theme (version_id, theme_id)",
                "SELECT v.version_id, t.theme_id",
                "FROM ws_document_version v",
                "JOIN ws_document d ON d.document_id = v.document_id",
                "JOIN ws_theme t ON t.name = " + _sql_str("Политика"),
                "WHERE d.title = " + _sql_str("Внутренняя переписка (фрагмент)") + " AND v.version_no = 1",
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)",
                "SELECT v.version_id, m.user_id, " + _sql_str("ready_for_publish") + "::ws_moderation_status,",
                "       " + _sql_timestamptz("2025-01-11 08:00:00+00") + ", " + _sql_str("Ок к публикации"),
                "FROM ws_document_version v",
                "JOIN ws_document d ON d.document_id = v.document_id",
                "JOIN ws_user m ON m.login = " + _sql_str("mod1"),
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам") + " AND v.version_no = 1",
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)",
                "SELECT v.version_id, m.user_id, " + _sql_str("sent_for_revision") + "::ws_moderation_status,",
                "       " + _sql_timestamptz("2025-01-16 10:00:00+00") + ", " + _sql_str("Нужны ссылки на первоисточник"),
                "FROM ws_document_version v",
                "JOIN ws_document d ON d.document_id = v.document_id",
                "JOIN ws_user m ON m.login = " + _sql_str("mod1"),
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам") + " AND v.version_no = 2",
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)",
                "SELECT v.version_id, m.user_id, " + _sql_str("rejected") + "::ws_moderation_status,",
                "       " + _sql_timestamptz("2025-02-02 11:00:00+00") + ", " + _sql_str("Персональные данные"),
                "FROM ws_document_version v",
                "JOIN ws_document d ON d.document_id = v.document_id",
                "JOIN ws_user m ON m.login = " + _sql_str("mod1"),
                "WHERE d.title = " + _sql_str("Внутренняя переписка (фрагмент)") + " AND v.version_no = 1",
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_favorite (user_id, document_id, added_at)",
                "SELECT u.user_id, d.document_id, " + _sql_timestamptz("2025-03-01 12:00:00+00"),
                "FROM ws_user u",
                "CROSS JOIN ws_document d",
                "WHERE u.login = " + _sql_str("reader1") + " AND d.title = " + _sql_str("Сводная таблица по контрактам"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)",
                "SELECT u.user_id, d.document_id, " + _sql_timestamptz("2025-03-05 14:22:00+00") + ", " + _sql_inet("192.168.1.10"),
                "FROM ws_user u",
                "CROSS JOIN ws_document d",
                "WHERE u.login = " + _sql_str("reader1") + " AND d.title = " + _sql_str("Сводная таблица по контрактам"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)",
                "SELECT u.user_id, d.document_id, " + _sql_timestamptz("2025-03-06 09:10:00+00") + ", " + _sql_inet("192.168.1.10"),
                "FROM ws_user u",
                "CROSS JOIN ws_document d",
                "WHERE u.login = " + _sql_str("reader1") + " AND d.title = " + _sql_str("Внутренняя переписка (фрагмент)"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("203.0.113.1") + ", " + _sql_timestamptz("2025-01-01 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("risk_user"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("203.0.113.2") + ", " + _sql_timestamptz("2025-01-02 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("risk_user"),
            ]
        )
    )

    # Пример по ТЗ (лимит 3 активных safe IP): 3 активных + 1 НЕактивный.
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.0.0.10") + ", " + _sql_timestamptz("2025-01-05 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_user"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.0.0.11") + ", " + _sql_timestamptz("2025-01-06 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_user"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.0.0.12") + ", " + _sql_timestamptz("2025-01-07 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_user"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.0.0.13") + ", " + _sql_timestamptz("2025-01-08 00:00:00+00") + ", FALSE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_user"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.1.0.1") + ", " + _sql_timestamptz("2025-01-09 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_author"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.1.0.2") + ", " + _sql_timestamptz("2025-01-10 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_author"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.1.0.3") + ", " + _sql_timestamptz("2025-01-11 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("safe3_author"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                "SELECT u.user_id, " + _sql_inet("198.51.100.99") + ", " + _sql_timestamptz("2025-04-01 07:00:00+00") + ", " + _sql_str("Подозрительный вход"),
                "FROM ws_user u WHERE u.login = " + _sql_str("risk_user"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_block_event (user_id, event_type, occurred_at, comment_text, actor_id)",
                "SELECT u.user_id, " + _sql_str("blocked") + ", " + _sql_timestamptz("2025-04-01 07:01:00+00") + ",",
                "       " + _sql_str("Автоблокировка: IP не в списке доверенных") + ", NULL",
                "FROM ws_user u WHERE u.login = " + _sql_str("risk_user"),
            ]
        )
    )
    stmts.append("UPDATE ws_user SET is_blocked = TRUE WHERE login = " + _sql_str("risk_user"))
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_block_event (user_id, event_type, occurred_at, comment_text, actor_id)",
                "SELECT u.user_id, " + _sql_str("unblocked") + ", " + _sql_timestamptz("2025-04-02 10:00:00+00") + ",",
                "       " + _sql_str("Проверка личности пройдена") + ", m.user_id",
                "FROM ws_user u",
                "CROSS JOIN ws_user m",
                "WHERE u.login = " + _sql_str("risk_user") + " AND m.login = " + _sql_str("mod1"),
            ]
        )
    )
    stmts.append("UPDATE ws_user SET is_blocked = FALSE WHERE login = " + _sql_str("risk_user"))

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_block_event (user_id, event_type, occurred_at, comment_text, actor_id)",
                "SELECT u.user_id, " + _sql_str("blocked") + ", " + _sql_timestamptz("2025-04-03 08:15:00+00") + ",",
                "       " + _sql_str("Автоблокировка: чтение с неизвестного IP") + ", NULL",
                "FROM ws_user u WHERE u.login = " + _sql_str("blocked_user"),
            ]
        )
    )

    # Запрос 3: заблокированный пользователь + устаревший safe IP (без входа с него) и свежий вход с другого IP.
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                "SELECT u.user_id, " + _sql_inet("10.250.1.1") + ", " + _sql_timestamptz("2025-01-15 00:00:00+00") + ", TRUE",
                "FROM ws_user u WHERE u.login = " + _sql_str("blocked_user"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                "SELECT u.user_id, "
                + _sql_inet("198.51.100.200")
                + ", NOW() - make_interval(days => 3), "
                + _sql_str("свежий вход с другого IP (заблокирован)"),
                "FROM ws_user u WHERE u.login = " + _sql_str("blocked_user"),
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)",
                "SELECT d.document_id, ua.user_id, NULL, um.user_id,",
                "       " + _sql_str("Упоминаю @mod1: нужна ли публикация в открытом доступе?") + ",",
                "       " + _sql_timestamptz("2025-03-10 16:00:00+00") + ", " + _sql_inet("10.0.0.2"),
                "FROM ws_document d",
                "JOIN ws_user ua ON ua.login = " + _sql_str("author1"),
                "JOIN ws_user um ON um.login = " + _sql_str("mod1"),
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам"),
            ]
        )
    )
    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)",
                "SELECT d.document_id, ur.user_id, c.comment_id, NULL,",
                "       " + _sql_str("Согласен с замечанием модератора по версии 2.") + ",",
                "       " + _sql_timestamptz("2025-03-11 11:30:00+00") + ", " + _sql_inet("192.168.1.10"),
                "FROM ws_document d",
                "JOIN ws_user ur ON ur.login = " + _sql_str("reader1"),
                "JOIN ws_comment c ON c.document_id = d.document_id AND c.author_id = (SELECT user_id FROM ws_user WHERE login = "
                + _sql_str("author1")
                + ")",
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам"),
                "LIMIT 1",
            ]
        )
    )

    stmts.append(
        "\n".join(
            [
                "INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)",
                "SELECT d.document_id, um.user_id, c2.comment_id, ua.user_id,",
                "       " + _sql_str("Ответ @reader1: учту, доработаю и пришлю новую версию.") + ",",
                "       " + _sql_timestamptz("2025-03-11 12:05:00+00") + ", " + _sql_inet("10.0.0.2"),
                "FROM ws_document d",
                "JOIN ws_user um ON um.login = " + _sql_str("mod1"),
                "JOIN ws_user ua ON ua.login = " + _sql_str("author1"),
                "JOIN ws_comment c2 ON c2.document_id = d.document_id AND c2.author_id = (SELECT user_id FROM ws_user WHERE login = "
                + _sql_str("reader1")
                + ")",
                "WHERE d.title = " + _sql_str("Сводная таблица по контрактам"),
                "LIMIT 1",
            ]
        )
    )

    return header + _join_statements(stmts)


def cmd_seed_sql(out: Path, check: bool) -> None:
    content = render_seed_sql()
    if check:
        existing = out.read_text(encoding="utf-8") if out.exists() else ""
        if existing != content:
            raise SystemExit(f"{out} не совпадает с генератором. Запустите: python3 Scripts/ws_tools.py seed-sql")
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")


def _rand_login(rng: random.Random) -> str:
    return "gen_" + "".join(rng.choices(string.ascii_lowercase + string.digits, k=10))


def _rand_title(rng: random.Random) -> str:
    return "Сгенерированный документ " + "".join(rng.choices(string.digits, k=6))


def _rand_text(rng: random.Random, n: int = 120) -> str:
    words = [
        "утечка",
        "документ",
        "версия",
        "модерация",
        "тематика",
        "информатор",
        "анализ",
        "данные",
    ]
    return " ".join(rng.choice(words) for _ in range(n // 6))


def _sql_dt_utc(dt: datetime) -> str:
    """Литерал TIMESTAMPTZ в UTC (+00)."""
    return _sql_timestamptz(dt.strftime("%Y-%m-%d %H:%M:%S+00"))


def render_test_data_sql(users: int, documents: int, versions_max: int, seed: int) -> str:
    """
    Объёмный тестовый набор в виде одного .sql файла.
    Предусловие: применены schema.sql и seed.sql (роли, темы из сида, пользователи модератор и т.д.).
    Связи задаются подзапросами по уникальным login/title/external_code (детерминированно от seed).
    """
    rng = random.Random(seed)
    base = datetime(2024, 6, 1, tzinfo=timezone.utc)
    weights_role = ["user"] * 5 + ["author"] * 3 + ["moderator"] * 1 + ["admin"] * 1
    status_cycle = ("ready_for_publish", "sent_for_revision", "rejected")

    lines: list[str] = [
        "-- AUTO-GENERATED TEST DATA",
        f"-- Generated by Scripts/ws_tools.py test-data | RNG seed = {seed}",
        "-- Prerequisites: psql -f db/schema.sql && psql -f db/seed.sql",
        "",
        "SET client_min_messages TO WARNING;",
        "",
        "-- ---- synthetic users ----",
    ]

    inserted: list[tuple[str, str]] = []  # (login, role_code)
    for i in range(users):
        code = rng.choice(weights_role)
        login = f"td_{seed % 100000}_{i:04d}_{_rand_login(rng)[-6:]}"
        if len(login) > 64:
            login = login[:64]
        extra = _rand_text(rng, 40)
        ip = f"{rng.randint(1, 223)}.{rng.randint(0, 255)}.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
        inserted.append((login, code))
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_user (login, extra_info, role_id, last_ip, is_blocked)",
                    f"SELECT {_sql_str(login)}, {_sql_str(extra)}, r.role_id, {_sql_inet(ip)}, FALSE",
                    "FROM ws_role r WHERE r.role_code = " + _sql_str(code),
                    "ON CONFLICT (login) DO NOTHING;",
                    "",
                ]
            )
        )

    lines.append("-- ---- safe IP для части синтетических читателей ----")
    for login, code in inserted:
        if code != "user":
            continue
        if rng.random() > 0.65:
            continue
        n_ips = rng.randint(1, 3)
        for k in range(n_ips):
            ip = f"10.{rng.randint(0, 255)}.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
            hours = k * 24
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                        f"SELECT u.user_id, {_sql_inet(ip)}, NOW() - make_interval(hours => {hours}), TRUE",
                        "FROM ws_user u WHERE u.login = " + _sql_str(login),
                        "ON CONFLICT (user_id, ip_address) DO NOTHING;",
                        "",
                    ]
                )
            )

    theme_name_pool = ["Политика", "Экономика", "Выборы"]
    lines.append("-- ---- дополнительные тематики (имена уникальны) ----")
    n_new_themes = min(15, documents)
    new_theme_names: list[str] = []
    for i in range(n_new_themes):
        nm = f"TD-тема-{seed}-{i}"
        new_theme_names.append(nm)
        parent = rng.choice(("Политика", "Экономика"))
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_theme (name, description, parent_id)",
                    "SELECT "
                    + _sql_str(nm)
                    + ", "
                    + _sql_str("Сгенерировано Scripts/ws_tools.py test-data")
                    + ", t.theme_id",
                    "FROM ws_theme t WHERE t.name = " + _sql_str(parent) + " LIMIT 1",
                    ";",
                    "",
                ]
            )
        )
    theme_name_pool = theme_name_pool + new_theme_names

    n_inf = max(5, documents // 5)
    informant_codes: list[str] = []
    lines.append("-- ---- информаторы (уникальный external_code) ----")
    for i in range(n_inf):
        ext = f"GEN-TD-{seed}-{i}-{rng.randint(1000, 99999)}"
        informant_codes.append(ext)
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_informant (external_code, extra_info, categories)",
                    f"VALUES ({_sql_str(ext)}, {_sql_str(_rand_text(rng, 20))}, ARRAY['ген']::text[]);",
                    "",
                ]
            )
        )

    seed_author_logins = ["author1", "coauthor1", "mod1", "admin1"]
    all_logins = sorted(
        {login for login, _ in inserted}
        | set(seed_author_logins)
        | {"reader1", "safe3_user", "risk_user", "blocked_user"}
    )
    authors_pool_logins = sorted(
        {login for login, rc in inserted if rc in ("author", "admin", "moderator")} | set(seed_author_logins)
    )
    if not authors_pool_logins:
        authors_pool_logins = list(seed_author_logins)

    moderator_subq = (
        "(SELECT u.user_id FROM ws_user u "
        "JOIN ws_role r ON r.role_id = u.role_id WHERE r.role_code = 'moderator' "
        "ORDER BY u.user_id LIMIT 1)"
    )

    lines.append("-- ---- документы, версии, модерация, просмотры, комментарии ----")
    for d_i in range(documents):
        primary_login = rng.choice(authors_pool_logins)
        suffix = "".join(rng.choices(string.digits, k=6))
        title = f"TD-DOC-{seed}-{d_i:04d}-{suffix}"
        dtype = rng.choice(("text", "table", "image", "archive"))
        lines.append(
            "\n".join(
                [
                    f"-- document {d_i + 1}/{documents}: {_sql_str(title)}",
                    "INSERT INTO ws_document (title, doc_type, primary_author_id, extra_info)",
                    "SELECT "
                    + _sql_str(title)
                    + ", "
                    + _sql_str(dtype)
                    + ", u.user_id, "
                    + _sql_str(_rand_text(rng, 60)),
                    "FROM ws_user u WHERE u.login = " + _sql_str(primary_login),
                    ";",
                    "",
                ]
            )
        )

        co_pool = [lg for lg in authors_pool_logins if lg != primary_login]
        rng.shuffle(co_pool)
        co_logins = co_pool[: rng.randint(0, min(2, len(co_pool)))]

        for lg in co_logins:
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_document_coauthor (document_id, coauthor_id)",
                        "SELECT d.document_id, u.user_id",
                        "FROM ws_document d",
                        "JOIN ws_user u ON u.login = " + _sql_str(lg),
                        "WHERE d.title = " + _sql_str(title),
                        "ON CONFLICT DO NOTHING;",
                        "",
                    ]
                )
            )

        edit_pool = [primary_login] + co_logins[:2]
        n_ver = rng.randint(1, max(1, versions_max))
        for vn in range(1, n_ver + 1):
            editor_login = rng.choice(edit_pool)
            ext = rng.choice(informant_codes)
            ts = base - timedelta(days=rng.randint(1, 600), hours=rng.randint(0, 23))
            prev_expr = (
                "NULL"
                if vn == 1
                else (
                    "(SELECT v.version_id FROM ws_document_version v "
                    "JOIN ws_document d ON d.document_id = v.document_id "
                    "WHERE d.title = "
                    + _sql_str(title)
                    + f" AND v.version_no = {vn - 1})"
                )
            )
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_document_version (",
                        "    document_id, version_no, previous_version_id, created_at,",
                        "    edited_by_user_id, informant_id, body_preview",
                        ")",
                        "SELECT d.document_id, "
                        + str(vn)
                        + ", "
                        + prev_expr
                        + ", "
                        + _sql_dt_utc(ts)
                        + ",",
                        "       ed.user_id, inf.informant_id, " + _sql_str(_rand_text(rng, 30)),
                        "FROM ws_document d",
                        "JOIN ws_user ed ON ed.login = " + _sql_str(editor_login),
                        "JOIN ws_informant inf ON inf.external_code = " + _sql_str(ext),
                        "WHERE d.title = " + _sql_str(title),
                        ";",
                        "",
                    ]
                )
            )

            k_th = rng.randint(1, min(3, len(theme_name_pool)))
            for tnm in rng.sample(theme_name_pool, k=k_th):
                lines.append(
                    "\n".join(
                        [
                            "INSERT INTO ws_version_theme (version_id, theme_id)",
                            "SELECT v.version_id, t.theme_id",
                            "FROM ws_document_version v",
                            "JOIN ws_document d ON d.document_id = v.document_id",
                            "JOIN ws_theme t ON t.name = " + _sql_str(tnm),
                            "WHERE d.title = " + _sql_str(title) + f" AND v.version_no = {vn}",
                            "ON CONFLICT DO NOTHING;",
                            "",
                        ]
                    )
                )

            st = status_cycle[(d_i + vn) % len(status_cycle)]
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_version_moderation (version_id, moderator_id, status, moderated_at, comment_text)",
                        "SELECT v.version_id, " + moderator_subq + ", " + _sql_str(st) + "::ws_moderation_status, ",
                        "       " + _sql_dt_utc(ts + timedelta(hours=1)) + ", " + _sql_str(_rand_text(rng, 25)),
                        "FROM ws_document_version v",
                        "JOIN ws_document d ON d.document_id = v.document_id",
                        "WHERE d.title = " + _sql_str(title) + f" AND v.version_no = {vn}",
                        ";",
                        "",
                    ]
                )
            )

        k_view = min(rng.randint(3, 12), max(1, len(all_logins)))
        viewers = rng.sample(all_logins, k=k_view)
        for vu in viewers:
            if rng.random() < 0.6:
                vts = base - timedelta(days=rng.randint(0, 90))
                cip = f"192.168.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
                lines.append(
                    "\n".join(
                        [
                            "INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)",
                            "SELECT u.user_id, d.document_id, " + _sql_dt_utc(vts) + ", " + _sql_inet(cip),
                            "FROM ws_user u",
                            "CROSS JOIN ws_document d",
                            "WHERE u.login = " + _sql_str(vu) + " AND d.title = " + _sql_str(title),
                            ";",
                            "",
                        ]
                    )
                )
            if rng.random() < 0.15:
                days_back = rng.randint(1, 40)
                lines.append(
                    "\n".join(
                        [
                            "INSERT INTO ws_favorite (user_id, document_id, added_at)",
                            "SELECT u.user_id, d.document_id, NOW() - make_interval(days => "
                            + str(days_back)
                            + ")",
                            "FROM ws_user u",
                            "CROSS JOIN ws_document d",
                            "WHERE u.login = " + _sql_str(vu) + " AND d.title = " + _sql_str(title),
                            "ON CONFLICT (user_id, document_id) DO NOTHING;",
                            "",
                        ]
                    )
                )

        if rng.random() < 0.4:
            aid = rng.choice(all_logins)
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_comment (document_id, author_id, parent_id, mention_user_id, body, created_at, client_ip)",
                        "SELECT d.document_id, u.user_id, NULL, NULL, "
                        + _sql_str(_rand_text(rng, 40))
                        + ", NOW(), "
                        + _sql_inet(f"10.0.{rng.randint(0, 255)}.1"),
                        "FROM ws_document d",
                        "JOIN ws_user u ON u.login = " + _sql_str(aid),
                        "WHERE d.title = " + _sql_str(title),
                        ";",
                        "",
                    ]
                )
            )

    lines.append("-- ---- история входов: общие IP для пар пользователей (запрос 1) ----")
    shared_ip_pool: list[str] = []
    for i in range(max(12, users // 6)):
        shared_ip_pool.append(
            f"185.{rng.randint(1, 254)}.{rng.randint(1, 254)}.{rng.randint(2, 254)}"
        )
    for ip in shared_ip_pool:
        k_users = rng.randint(2, min(4, len(all_logins)))
        group = rng.sample(all_logins, k=k_users)
        for login in group:
            n_logins = rng.randint(2, 7)
            for _ in range(n_logins):
                days_ago = rng.randint(5, 400)
                hours = rng.randint(0, 23)
                mins = rng.choice((0, 15, 30, 45))
                lines.append(
                    "\n".join(
                        [
                            "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                            "SELECT u.user_id, "
                            + _sql_inet(ip)
                            + ", NOW() - make_interval(days => "
                            + str(days_ago)
                            + ", hours => "
                            + str(hours)
                            + ", mins => "
                            + str(mins)
                            + "), "
                            + _sql_str("test-data shared IP"),
                            "FROM ws_user u WHERE u.login = " + _sql_str(login) + ";",
                            "",
                        ]
                    )
                )

    lines.append("-- ---- safe IP: устаревшие / без входов (запрос 3) ----")
    stale_candidates = [lg for lg, rc in inserted if rc == "user"][: max(10, users // 4)]
    for login in stale_candidates:
        ip_stale = f"10.200.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
        ip_other = f"10.201.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                    "SELECT u.user_id, "
                    + _sql_inet(ip_stale)
                    + ", NOW() - make_interval(days => 90), TRUE",
                    "FROM ws_user u WHERE u.login = " + _sql_str(login),
                    "ON CONFLICT (user_id, ip_address) DO NOTHING;",
                    "",
                ]
            )
        )
        if rng.random() < 0.25:
            continue
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                    "SELECT u.user_id, "
                    + _sql_inet(ip_stale)
                    + ", NOW() - make_interval(days => "
                    + str(rng.randint(40, 120))
                    + "), "
                    + _sql_str("устаревший safe IP"),
                    "FROM ws_user u WHERE u.login = " + _sql_str(login) + ";",
                    "",
                ]
            )
        )
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                    "SELECT u.user_id, "
                    + _sql_inet(ip_other)
                    + ", NOW() - make_interval(days => "
                    + str(rng.randint(1, 10))
                    + ", hours => "
                    + str(rng.randint(0, 12))
                    + "), "
                    + _sql_str("свежий вход с другого IP"),
                    "FROM ws_user u WHERE u.login = " + _sql_str(login) + ";",
                    "",
                ]
            )
        )

    lines.append("-- ---- запрос 3: заблокированные + устаревшие safe IP ----")
    blocked_q3: list[str] = []
    if "blocked_user" in all_logins:
        blocked_q3.append("blocked_user")
    for login in stale_candidates:
        if login in blocked_q3 or len(blocked_q3) >= 4:
            break
        blocked_q3.append(login)
        lines.append(
            "UPDATE ws_user SET is_blocked = TRUE WHERE login = " + _sql_str(login) + ";"
        )
    for login in blocked_q3:
        if login == "blocked_user":
            continue
        ip_stale = f"10.210.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
        ip_other = f"10.211.{rng.randint(0, 255)}.{rng.randint(1, 254)}"
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_safe_ip (user_id, ip_address, added_at, is_active)",
                    "SELECT u.user_id, "
                    + _sql_inet(ip_stale)
                    + ", NOW() - make_interval(days => 120), TRUE",
                    "FROM ws_user u WHERE u.login = " + _sql_str(login),
                    "ON CONFLICT (user_id, ip_address) DO NOTHING;",
                    "",
                ]
            )
        )
        if rng.random() < 0.4:
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                        "SELECT u.user_id, "
                        + _sql_inet(ip_stale)
                        + ", NOW() - make_interval(days => "
                        + str(rng.randint(45, 100))
                        + "), "
                        + _sql_str("устаревший safe IP (заблокирован)"),
                        "FROM ws_user u WHERE u.login = " + _sql_str(login) + ";",
                        "",
                    ]
                )
            )
        lines.append(
            "\n".join(
                [
                    "INSERT INTO ws_login_history (user_id, ip_address, logged_at, extra_info)",
                    "SELECT u.user_id, "
                    + _sql_inet(ip_other)
                    + ", NOW() - make_interval(days => "
                    + str(rng.randint(1, 7))
                    + "), "
                    + _sql_str("свежий вход с другого IP (заблокирован)"),
                    "FROM ws_user u WHERE u.login = " + _sql_str(login) + ";",
                    "",
                ]
            )
        )

    lines.append("-- ---- просмотры: прошлая и позапрошлая недели (запрос 4) ----")
    activity_users = rng.sample(all_logins, k=min(20, max(7, len(all_logins) // 3)))
    doc_offset = 0
    for ui, login in enumerate(activity_users):
        doc_offset = (ui * 3) % max(1, documents)
        for day in range(7):
            if rng.random() > 0.55:
                continue
            hour = rng.choice(range(0, 24, 3))
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)",
                        "SELECT u.user_id, d.document_id,",
                        "       date_trunc('week', CURRENT_DATE) - interval '1 week'",
                        "         + make_interval(days => " + str(day) + ", hours => " + str(hour) + "),",
                        "       " + _sql_inet(f"172.20.{ui % 255}.{day + 1}"),
                        "FROM ws_user u",
                        "JOIN (SELECT document_id FROM ws_document ORDER BY document_id",
                        "      OFFSET " + str(doc_offset) + " LIMIT 1) d ON TRUE",
                        "WHERE u.login = " + _sql_str(login) + ";",
                        "",
                    ]
                )
            )
        if rng.random() < 0.85:
            pw_day = rng.randint(0, 6)
            pw_hour = rng.choice(range(0, 24, 3))
            lines.append(
                "\n".join(
                    [
                        "INSERT INTO ws_view_history (user_id, document_id, viewed_at, client_ip)",
                        "SELECT u.user_id, d.document_id,",
                        "       date_trunc('week', CURRENT_DATE) - interval '2 weeks'",
                        "         + make_interval(days => " + str(pw_day) + ", hours => " + str(pw_hour) + "),",
                        "       " + _sql_inet(f"172.21.{ui % 255}.{pw_day + 1}"),
                        "FROM ws_user u",
                        "JOIN (SELECT document_id FROM ws_document ORDER BY document_id",
                        "      OFFSET " + str((doc_offset + 1) % max(1, documents)) + " LIMIT 1) d ON TRUE",
                        "WHERE u.login = " + _sql_str(login) + ";",
                        "",
                    ]
                )
            )

    return "\n".join(lines).rstrip() + "\n"


def cmd_test_data(out: Path, users: int, documents: int, versions_max: int, seed: int | None) -> None:
    seed_val = seed if seed is not None else random.randrange(1 << 30)
    print(f"RNG seed = {seed_val}")
    content = render_test_data_sql(
        users=users, documents=documents, versions_max=versions_max, seed=seed_val
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"Записано: {out}")


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Утилиты WikiSneaks")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_seed = sub.add_parser("seed-sql", help="Сгенерировать db/seed.sql")
    p_seed.add_argument("--out", type=Path, default=Path("db/seed.sql"), help="Куда записать seed.sql")
    p_seed.add_argument("--check", action="store_true", help="Не писать файл, только проверить совпадение")

    p_td = sub.add_parser(
        "test-data",
        help="Сгенерировать db/test_data.sql (объёмные тестовые данные, без подключения к БД)",
    )
    p_td.add_argument(
        "--out",
        type=Path,
        default=Path("db/test_data.sql"),
        help="Куда записать SQL (применить после seed: psql -f db/test_data.sql)",
    )
    p_td.add_argument("--users", type=int, default=40, help="Сколько новых пользователей")
    p_td.add_argument("--documents", type=int, default=25, help="Сколько новых документов")
    p_td.add_argument("--versions-max", type=int, default=4, help="Макс. версий на документ")
    p_td.add_argument("--seed", type=int, default=None, help="Seed RNG для воспроизводимости")

    args = p.parse_args(argv)
    if args.cmd == "seed-sql":
        cmd_seed_sql(out=args.out, check=args.check)
        return
    if args.cmd == "test-data":
        cmd_test_data(
            out=args.out,
            users=args.users,
            documents=args.documents,
            versions_max=args.versions_max,
            seed=args.seed,
        )
        return

    raise SystemExit("Unknown command")


if __name__ == "__main__":
    main()

